package net.sf.xapp.net.common.types;


/**
 * Generated 13-Mar-2012 20:16:05
 */
public enum Country
{
    Afghanistan("AF", "AFG"),
    Albania("AL", "ALB"),
    Algeria("DZ", "DZA"),
    American_Samoa("AS", "ASM"),
    Andorra("AD", "AND"),
    Angola("AO", "AGO"),
    Anguilla("AI", "AIA"),
    Antigua_and_Barbuda("AG", "ATG"),
    Argentina("AR", "ARG"),
    Armenia("AM", "ARM"),
    Aruba("AW", "ABW"),
    Australia("AU", "AUS"),
    Austria("AT", "AUT"),
    Azerbaijan("AZ", "AZE"),
    Bahamas("BS", "BHS"),
    Bahrain("BH", "BHR"),
    Bangladesh("BD", "BGD"),
    Barbados("BB", "BRB"),
    Belarus("BY", "BLR"),
    Belgium("BE", "BEL"),
    Belize("BZ", "BLZ"),
    Benin("BJ", "BEN"),
    Bermuda("BM", "BMU"),
    Bhutan("BT", "BTN"),
    Bolivia("BO", "BOL"),
    Bosnia_and_Herzegovina("BA", "BIH"),
    Botswana("BW", "BWA"),
    Bouvet_Island("BV", "BVT"),
    Brazil("BR", "BRA"),
    British_Indian_Ocean_Territory("IO", "IOT"),
    Brunei_Darussalam("BN", "BRN"),
    Bulgaria("BG", "BGR"),
    Burkina_Faso("BF", "BFA"),
    Burundi("BI", "BDI"),
    Cambodia("KH", "KHM"),
    Cameroon("CM", "CMR"),
    Canada("CA", "CAN"),
    Cape_Verde("CV", "CPV"),
    Cayman_Islands("KY", "CYM"),
    Central_African_Republic("CF", "CAF"),
    Chad("TD", "TCD"),
    Chile("CL", "CHL"),
    China("CN", "CHN"),
    Christmas_Island("CX", "CXR"),
    Cocos__Islands("CC", "CCK"),
    Colombia("CO", "COL"),
    Comoros("KM", "COM"),
    Congo("CG", "COG"),
    Cook_Islands("CK", "COK"),
    Costa_Rica("CR", "CRI"),
    Croatia("HR", "HRV"),
    Cuba("CU", "CUB"),
    Cyprus("CY", "CYP"),
    Czech_Republic("CZ", "CZE"),
    Denmark("DK", "DNK"),
    Djibouti("DJ", "DJI"),
    Dominica("DM", "DMA"),
    Dominican_Republic("DO", "DOM"),
    Ecuador("EC", "ECU"),
    Egypt("EG", "EGY"),
    El_Salvador("SV", "SLV"),
    Equatorial_Guinea("GQ", "GNQ"),
    Eritrea("ER", "ERI"),
    Estonia("EE", "EST"),
    Ethiopia("ET", "ETH"),
    Falkland_Islands("FK", "FLK"),
    Faroe_Islands("FO", "FRO"),
    Fiji("FJ", "FJI"),
    Finland("FI", "FIN"),
    France("FR", "FRA"),
    French_Guiana("GF", "GUF"),
    French_Polynesia("PF", "PYF"),
    French_Southern_Territories("TF", "ATF"),
    Gabon("GA", "GAB"),
    Gambia("GM", "GMB"),
    Georgia("GE", "GEO"),
    Germany("DE", "DEU"),
    Ghana("GH", "GHA"),
    Gibraltar("GI", "GIB"),
    Greece("GR", "GRC"),
    Greenland("GL", "GRL"),
    Grenada("GD", "GRD"),
    Guadeloupe("GP", "GLP"),
    Guam("GU", "GUM"),
    Guatemala("GT", "GTM"),
    Guinea("GN", "GIN"),
    Guinea_Bissau("GW", "GNB"),
    Guyana("GY", "GUY"),
    Haiti("HT", "HTI"),
    Heard_Island_and_McDonald_Islands("HM", "HMD"),
    Honduras("HN", "HND"),
    Hong_Kong("HK", "HKG"),
    Hungary("HU", "HUN"),
    Iceland("IS", "ISL"),
    India("IN", "IND"),
    Indonesia("ID", "IDN"),
    Iran("IR", "IRN"),
    Iraq("IQ", "IRQ"),
    Ireland("IE", "IRL"),
    Israel("IL", "ISR"),
    Italy("IT", "ITA"),
    Ivory_Coast("CI", "CIV"),
    Jamaica("JM", "JAM"),
    Japan("JP", "JPN"),
    Jordan("JO", "JOR"),
    Kazakhstan("KZ", "KAZ"),
    Kenya("KE", "KEN"),
    Kiribati("KI", "KIR"),
    Korea("KR", "KOR"),
    Kuwait("KW", "KWT"),
    Kyrgyzstan("KG", "KGZ"),
    Laos("LA", "LAO"),
    Latvia("LV", "LVA"),
    Lebanon("LB", "LBN"),
    Lesotho("LS", "LSO"),
    Liberia("LR", "LBR"),
    Libya("LY", "LBY"),
    Liechtenstein("LI", "LIE"),
    Lithuania("LT", "LTU"),
    Luxembourg("LU", "LUX"),
    Macao("MO", "MAC"),
    Macedonia("MK", "MKD"),
    Madagascar("MG", "MDG"),
    Malawi("MW", "MWI"),
    Malaysia("MY", "MYS"),
    Maldives("MV", "MDV"),
    Mali("ML", "MLI"),
    Malta("MT", "MLT"),
    Marshall_Islands("MH", "MHL"),
    Martinique("MQ", "MTQ"),
    Mauritania("MR", "MRT"),
    Mauritius("MU", "MUS"),
    Mayotte("YT", "MYT"),
    Mexico("MX", "MEX"),
    Micronesia("FM", "FSM"),
    Moldova("MD", "MDA"),
    Monaco("MC", "MCO"),
    Mongolia("MN", "MNG"),
    Montenegro("ME", "MNE"),
    Montserrat("MS", "MSR"),
    Morocco("MA", "MAR"),
    Mozambique("MZ", "MOZ"),
    Myanmar("MM", "MMR"),
    Namibia("NA", "NAM"),
    Nauru("NR", "NRU"),
    Nepal("NP", "NPL"),
    Netherlands("NL", "NLD"),
    New_Caledonia("NC", "NCL"),
    New_Zealand("NZ", "NZL"),
    Nicaragua("NI", "NIC"),
    Niger("NE", "NER"),
    Nigeria("NG", "NGA"),
    Niue("NU", "NIU"),
    Norfolk_Island("NF", "NFK"),
    Northern_Mariana_Islands("MP", "MNP"),
    Norway("NO", "NOR"),
    Oman("OM", "OMN"),
    Pakistan("PK", "PAK"),
    Palau("PW", "PLW"),
    Palestinian_Territory("PS", "PSE"),
    Panama("PA", "PAN"),
    Papua_New_Guinea("PG", "PNG"),
    Paraguay("PY", "PRY"),
    Peru("PE", "PER"),
    Philippines("PH", "PHL"),
    Pitcairn("PN", "PCN"),
    Poland("PL", "POL"),
    Portugal("PT", "PRT"),
    Puerto_Rico("PR", "PRI"),
    Qatar("QA", "QAT"),
    Romania("RO", "ROU"),
    Russian_Federation("RU", "RUS"),
    Rwanda("RW", "RWA"),
    Reunion("RE", "REU"),
    Saint_Helena("SH", "SHN"),
    Saint_Kitts_and_Nevis("KN", "KNA"),
    Saint_Lucia("LC", "LCA"),
    Saint_Pierre_and_Miquelon("PM", "SPM"),
    Saint_Vincent_and_the_Grenadines("VC", "VCT"),
    Samoa("WS", "WSM"),
    San_Marino("SM", "SMR"),
    Sao_Tome_and_Principe("ST", "STP"),
    Saudi_Arabia("SA", "SAU"),
    Senegal("SN", "SEN"),
    Serbia("RS", "SRB"),
    Seychelles("SC", "SYC"),
    Sierra_Leone("SL", "SLE"),
    Singapore("SG", "SGP"),
    Slovakia("SK", "SVK"),
    Slovenia("SI", "SVN"),
    Solomon_Islands("SB", "SLB"),
    Somalia("SO", "SOM"),
    South_Africa("ZA", "ZAF"),
    South_Georgia_and_the_South_Sandwich_Islands("GS", "SGS"),
    Spain("ES", "ESP"),
    Sri_Lanka("LK", "LKA"),
    Sudan("SD", "SDN"),
    Suriname("SR", "SUR"),
    Svalbard_and_Jan_Mayen("SJ", "SJM"),
    Swaziland("SZ", "SWZ"),
    Sweden("SE", "SWE"),
    Switzerland("CH", "CHE"),
    Syrian_Arab_Republic("SY", "SYR"),
    Taiwan("TW", "TWN"),
    Tajikistan("TJ", "TJK"),
    Tanzania("TZ", "TZA"),
    Thailand("TH", "THA"),
    Timor_Leste("TL", "TLS"),
    Togo("TG", "TGO"),
    Tokelau("TK", "TKL"),
    Tonga("TO", "TON"),
    Trinidad_and_Tobago("TT", "TTO"),
    Tunisia("TN", "TUN"),
    Turkey("TR", "TUR"),
    Turkmenistan("TM", "TKM"),
    Turks_and_Caicos_Islands("TC", "TCA"),
    Tuvalu("TV", "TUV"),
    Uganda("UG", "UGA"),
    Ukraine("UA", "UKR"),
    United_Arab_Emirates("AE", "ARE"),
    United_Kingdom("GB", "GBR"),
    United_States("US", "USA"),
    United_States_Minor_Outlying_Islands("UM", "UMI"),
    Uruguay("UY", "URY"),
    Uzbekistan("UZ", "UZB"),
    Vanuatu("VU", "VUT"),
    Vatican_City("VA", "VAT"),
    Venezuela("VE", "VEN"),
    Viet_Nam("VN", "VNM"),
    Virgin_Islands("VI", "VIR"),
    Wallis_and_Futuna("WF", "WLF"),
    Western_Sahara("EH", "ESH"),
    Yemen("YE", "YEM"),
    Zambia("ZM", "ZMB"),
    Zimbabwe("ZW", "ZWE");

    private final String isoCode2;
    private final String isoCode3;

    Country(String isoCode2, String isoCode3)
    {
        this.isoCode2 = isoCode2;
        this.isoCode3 = isoCode3;
    }

    public String getIsoCode2()
    {
        return isoCode2;
    }

    public String getIsoCode3()
    {
        return isoCode3;
    }

    public static Country decode(String iso3digitCode)
    {
        for (Country country : values())
        {
            if (country.getIsoCode3().equals(iso3digitCode))
            {
                return country;
            }
        }
        return null;
    }
}
